#Set common info
set(CPACK_PACKAGE_NAME
	${PROJECT_NAME}
	)
set(CPACK_PACKAGE_VENDOR
	${${PROJECT_NAME}_ORGANIZATION}
	CACHE STRING
	"Organization name"
	)
set(CPACK_PACKAGE_CONTACT
	${${PROJECT_NAME}_SUPPORT_ADDRESS}
	CACHE STRING
	"Contact information"
	)
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY
	"Development by ${${PROJECT_NAME}_AUTHORS}"
	CACHE STRING
	"Description"
	)
set(CPACK_RESOURCE_FILE_LICENSE
	${${PROJECT_NAME}_LICENCE}
	)

#Set version info

set(CPACK_PACKAGE_VERSION
	"${${PROJECT_NAME}_REVISION_VERSION}"
	)
set(CPACK_PACKAGE_VERSION_PATH
	"${${PROJECT_NAME}_SOURCE_PATH}"
	)


#Set directories
set(CPACK_PACKAGE_INSTALL_DIRECTORY
	${PROJECT_NAME}
	)
if(NOT "${CMAKE_INSTALL_PREFIX}" STREQUAL "")
	set(CPACK_OUTPUT_FILE_PREFIX
		${CMAKE_INSTALL_PREFIX}/package
		CACHE PATH
		"Path to save packages"
		)
endif()

if ("${CPACK_OUTPUT_FILE_PREFIX}" STREQUAL ""
		)
	set(CPACK_OUTPUT_FILE_PREFIX
		"./package"
		CACHE PATH
		"Path to save packages"
		FORCE
		)
endif()
mark_as_advanced (CPACK_OUTPUT_FILE_PREFIX
				  CPACK_PACKAGE_VENDOR
				  CPACK_PACKAGE_CONTACT
				  CPACK_PACKAGE_DESCRIPTION_SUMMARY
				  )

#set components
set(CPACK_COMPONENTS_ALL
	applications
	libraries
	cmake
	headers
	config
	examples
	tests
	docs
	)
set(_LICENSE_INSTALL_PATH "${${PROJECT_NAME}_INSTALL_PREFIX}${CMAKE_INSTALL_DATAROOTDIR}/${PROJECT_NAME}/license")

if (WIN32)
	set(_LICENSE_INSTALL_PATH_DEV "${_LICENSE_INSTALL_PATH}")
	set(_LICENSE_INSTALL_PATH_RUNTIME "${_LICENSE_INSTALL_PATH}")
else()
	set(_LICENSE_INSTALL_PATH_DEV "${_LICENSE_INSTALL_PATH}/${PROJECT_NAME}-Development")
	set(_LICENSE_INSTALL_PATH_RUNTIME "${_LICENSE_INSTALL_PATH}/${PROJECT_NAME}-Runtime")
endif ()

install(FILES
		${${PROJECT_NAME}_LICENCE}
		DESTINATION
		"${_LICENSE_INSTALL_PATH_RUNTIME}"
		COMPONENT applications)
install(FILES
		${${PROJECT_NAME}_LICENCE}
		DESTINATION
		"${_LICENSE_INSTALL_PATH_RUNTIME}"
		COMPONENT libraries)
install(FILES
		${${PROJECT_NAME}_LICENCE}
		DESTINATION
		"${_LICENSE_INSTALL_PATH_RUNTIME}"
		COMPONENT config)

install(FILES
		${${PROJECT_NAME}_LICENCE}
		DESTINATION
		"${_LICENSE_INSTALL_PATH_DEV}"
		COMPONENT cmake)
install(FILES
		${${PROJECT_NAME}_LICENCE}
		DESTINATION
		"${_LICENSE_INSTALL_PATH_DEV}"
		COMPONENT headers)

install(FILES
		${${PROJECT_NAME}_LICENCE}
		DESTINATION
		"${_LICENSE_INSTALL_PATH_DEV}"
		COMPONENT examples)
install(FILES
		${${PROJECT_NAME}_LICENCE}
		DESTINATION
		"${_LICENSE_INSTALL_PATH_DEV}"
		COMPONENT tests)
install(FILES
		${${PROJECT_NAME}_LICENCE}
		DESTINATION
		"${_LICENSE_INSTALL_PATH_DEV}"
		COMPONENT docs)

set(CPACK_COMPONENT_GROUP_DEVELOPMENT_DESCRIPTION
	"All tools you'll ever need to develop"
	)
set(CPACK_COMPONENT_GROUP_RUNTIME_DESCRIPTION
	"For user only
")

set(CPACK_COMPONENT_APPLICATIONS_GROUP
	"Runtime"
	)
set(CPACK_COMPONENT_CONFIG_GROUP
	"Runtime"
	)
set(CPACK_COMPONENT_LIBRARIES_GROUP
	"Runtime"
	)

set(CPACK_COMPONENT_TESTS_GROUP
	"Development"
	)
set(CPACK_COMPONENT_CMAKE_GROUP
	"Development"
	)
set(CPACK_COMPONENT_HEADERS_GROUP
	"Development"
	)
set(CPACK_COMPONENT_EXAMPLES_GROUP
	"Development"
	)
set(CPACK_COMPONENT_DOCS_GROUP
	"Development"
	)

set(CPACK_COMPONENT_HEADERS_DEPENDS
	libraries
	)
set(CPACK_COMPONENT_APPLICATIONS_DEPENDS
	libraries
	config
	)
set(CPACK_COMPONENT_EXAMPLES_DEPENDS
	applications
	headers
	cmake
	)
set(CPACK_COMPONENT_TESTS_DEPENDS
	libraries
	)

#Set variables speceified to DEB
set(CPACK_DEB_PACKAGE_COMPONENT ON)
set(CPACK_DEB_COMPONENT_INSTALL ON)
set(CPACK_DEBIAN_ENABLE_COMPONENT_DEPENDS ON)
set(CPACK_DEBIAN_PACKAGE_MAINTAINER
	${CPACK_PACKAGE_VENDOR}
	)
set(CPACK_DEBIAN_RUNTIME_PACKAGE_SECTION "libs")
set(CPACK_DEBIAN_DEVELOPMENT_PACKAGE_SECTION "devel")

if(NOT "${CPACK_PACKAGE_VERSION}" STREQUAL "")
	set(CPACK_DEBIAN_PACKAGE_VERSION
		"${CPACK_PACKAGE_VERSION}"
		)
else()
	set(CPACK_DEBIAN_PACKAGE_VERSION
		"0"
		)
endif()

#Set variables speceified to NSIS
if(WIN32 AND NOT UNIX)
	set(CPACK_NSIS_DISPLAY_NAME
		"${PROJECT_NAME} rev. ${${PROJECT_NAME}_REVISION_VERSION}"
		)
	set(CPACK_NSIS_MODIFY_PATH ON)
	set(CPACK_NSIS_CONTACT
		${CPACK_PACKAGE_CONTACT}
		)
	set(CPACK_NSIS_COMPRESSORCPACK_NSIS_PACKAGE_NAME
		"lzma"
		)
	#Create link to cmake directory
	set(CPACK_NSIS_EXTRA_INSTALL_COMMANDS
		"CreateShortCut '$INSTDIR\\\\${CMAKE_INSTALL_BINDIR}\\\\${CMAKE_PACKAGE_INSTALL_DIR}.lnk' '$INSTDIR\\\\${CMAKE_PACKAGE_INSTALL_DIR}\\\\'"
     )
	set(CPACK_NSIS_EXTRA_UNINSTALL_COMMANDS
		"Delete '$INSTDIR\\\\${CMAKE_INSTALL_BINDIR}\\\\${CMAKE_PACKAGE_INSTALL_DIR}.lnk'"
		)

	list(APPEND CPACK_NSIS_CREATE_ICONS_EXTRA
		 "CreateShortCut '$DESKTOP\\\\${PROJECT_NAME}.lnk' '$INSTDIR\\\\'")

	list(APPEND CPACK_NSIS_DELETE_ICONS_EXTRA
		 "Delete '$DESKTOP\\\\${PROJECT_NAME}.lnk'")

	if (MINGW)
		get_filename_component(CXX_PATH ${CMAKE_CXX_COMPILER} DIRECTORY)

		set(_MINGW_RUNTIME_LIBS "")
		if (EXISTS ${CXX_PATH}/libgcc_s_dw2-1.dll)
			list(APPEND _MINGW_RUNTIME_LIBS ${CXX_PATH}/libgcc_s_dw2-1.dll)
		endif ()

		if (EXISTS ${CXX_PATH}/libstdc++-6.dll)
			list(APPEND _MINGW_RUNTIME_LIBS ${CXX_PATH}/libstdc++-6.dll)
		endif ()

		if (EXISTS ${CXX_PATH}/mingwm10.dll)
			list(APPEND _MINGW_RUNTIME_LIBS ${CXX_PATH}/mingwm10.dll)
		endif ()

		if (EXISTS ${CXX_PATH}/libwinpthread-1.dll)
			list(APPEND _MINGW_RUNTIME_LIBS ${CXX_PATH}/libwinpthread-1.dll)
		endif ()

		if (_MINGW_RUNTIME_LIBS)
			install(FILES
					${_MINGW_RUNTIME_LIBS}
					DESTINATION
					"${${PROJECT_NAME}_INSTALL_PREFIX}${CMAKE_INSTALL_BINDIR}"
					COMPONENT applications)
		endif ()
	endif()
endif()

#set generators
if(NOT CPACK_GENERATOR)
	if(WIN32)
		set(CPACK_GENERATOR "NSIS")
	elseif(UNIX)
		find_program(LSB_RELEASE_EXEC lsb_release)
		if(EXISTS ${LSB_RELEASE_EXEC})
			execute_process(COMMAND
							${LSB_RELEASE_EXEC}
							-si
							OUTPUT_VARIABLE _DISTIBUTION
							OUTPUT_STRIP_TRAILING_WHITESPACE
							)
			if(_DISTIBUTION STREQUAL "Debian"
			   OR _DISTIBUTION STREQUAL "Ubuntu"
			   OR _DISTIBUTION MATCHES "AstraLinux.*"
			   )
				set(CPACK_GENERATOR "DEB")
			elseif(_DISTIBUTION MATCHES "RedHat.*")
				set(CPACK_GENERATOR "RPM")
			endif()
		endif()
	endif()
endif()
if(EXISTS "${CMAKE_CURRENT_LIST_DIR}/../${PROJECT_NAME}_CPack.cmake")
	include("${CMAKE_CURRENT_LIST_DIR}/../${PROJECT_NAME}_CPack.cmake")
endif()
include(CPack)
