#ifndef @PROJECT_NAME@_CONFIG_H
#define @PROJECT_NAME@_CONFIG_H

#cmakedefine CMAKE_INSTALL_FULL_SYSCONFDIR "@CMAKE_INSTALL_FULL_SYSCONFDIR@"
#cmakedefine CMAKE_INSTALL_FULL_LOCALSTATEDIR "@CMAKE_INSTALL_FULL_LOCALSTATEDIR@"
#cmakedefine CMAKE_INSTALL_FULL_DATAROOTDIR "@CMAKE_INSTALL_FULL_DATAROOTDIR@"
#cmakedefine UDT_GUI_PATH "@UDT_GUI_PATH@"
#cmakedefine UDT_CONFIG_DEFAULT_PATH "@UDT_CONFIG_DEFAULT_PATH@"

#endif /* @PROJECT_NAME@_CONFIG_H */
