name: CI

on: [push]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name:
        run: cmake --version
      - name: configure
        run: mkdir build && cd build && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Debug ..
      - name: build
        run: cd build && cmake --build . --target install
      - name: Testing
        run: |
         cd build/binary/bin && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../lib
         (timeout --signal=SIGABRT 10 ./Kernel -c ./test/test_kernel.json &) && (timeout --signal=SIGABRT 10 ./test_rtc) && kill -SIGINT `pgrep Kernel`
