name: CI

on: [push]

jobs:
  build-ubuntu:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
          ubuntu-gcc-6,
          ubuntu-gcc-9,
          ubuntu-clang-6,
#          ubuntu-clang-9,
        ]
        include:
          - name: ubuntu-gcc-6
            os: ubuntu-16.04
            compiler: gcc
            version: "6"
            configuration: release

          - name: ubuntu-gcc-9
            os: ubuntu-latest
            compiler: gcc
            version: "9"
            configuration: release

          - name: ubuntu-clang-6
            os: ubuntu-16.04
            compiler: clang
            version: "6.0"
            configuration: release

    steps:
      - uses: actions/checkout@v1

      - name: Install (Linux)
        if: runner.os == 'Linux'
        run: |
            # LLVM 9 is not yet in Bionic's repositories.
            #sudo add-apt-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-9 main"
            sudo apt-get update
            #sudo apt-get install -y ninja-build clang-tidy-9
            sudo apt-get install libboost-all-dev
            #sudo ln -s /usr/bin/clang-tidy-9 /usr/local/bin/clang-tidy
            if [ "${{ matrix.compiler }}" = "gcc" ]; then
              sudo apt-get install -y g++-${{ matrix.version }}
              echo "::set-env name=CC::gcc-${{ matrix.version }}"
              echo "::set-env name=CXX::g++-${{ matrix.version }}"
            else
              sudo apt-get install -y clang-${{ matrix.version }}
              echo "::set-env name=CC::clang-${{ matrix.version }}"
              echo "::set-env name=CXX::clang++-${{ matrix.version }}"
            fi
      - name: Print version
        run: |
          cmake --version
          if [ "${{ matrix.compiler }}" = "gcc" ]; then
            gcc --version
          else
            clang --version
          fi

      - name: configure
        run: mkdir build && cd build && cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=/usr/include/boost ..
      - name: build
        run: cd build && cmake --build . --target install
      - name:  SHARE unit test
          shell: bash
          run: |
            cd build/binary/bin
            ./unit_tests
      - name: Testing RTC
        run: |
         cd build/binary/bin && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../lib
         (timeout --signal=SIGABRT 100 ./Kernel -c ./test/test_kernel.json &) && (timeout --signal=SIGABRT 100 ./test_rtc) && kill -SIGINT `pgrep Kernel`
      - name: Testing inheritance
        run: |
          cd build/binary/bin && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../lib
          (timeout --signal=SIGABRT 100 ./Kernel &) && (timeout --signal=SIGABRT 100 ./test_inheritance) && kill -SIGINT `pgrep Kernel`
      - name: Testing errors
        run: |
          cd build/binary/bin && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../lib
          (timeout --signal=SIGABRT 100 ./Kernel &) && (timeout --signal=SIGABRT 100 ./test_errors) && kill -SIGINT `pgrep Kernel`
      - name: Testing selection
        run: |
          cd build/binary/bin && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../lib
          (timeout --signal=SIGABRT 100 ./Kernel &) && (timeout --signal=SIGABRT 100 ./test_selection) && kill -SIGINT `pgrep Kernel`
      - name: Testing high load
        if: matrix.configuration == 'Release'
        run: |
          cd build/binary/bin && export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:../lib
          (timeout --signal=SIGABRT 100 ./Kernel &) && (timeout --signal=SIGABRT 100 ./test_of_speed) && kill -SIGINT `pgrep Kernel`

      - name: Store artifact
        uses: actions/upload-artifact@master
        with:
          name: UDT-bunary-${{ matrix.name }}-${{ github.sha }}
          path: build/binary/

  build_windows:
    strategy:
      matrix:
        configuration: [Release, Debug]
        compiler: [MSVC]
        arch: [Win32, x64]
    name: Windows
    runs-on: windows-2019
    steps:
      - name: Prepare Environment
        run: |
          choco install wget --no-progress
          choco install tartool --no-progress
          choco install windows-kill --no-progress
          choco install grep --no-progress
          choco install awk --no-progress
      - uses: actions/checkout@v1

      - name: Install boost
        shell: bash
        run: |
          wget -nv http://downloads.sourceforge.net/project/boost/boost/1.56.0/boost_1_56_0.tar.bz2
          tar --bzip2 -xf boost_1_56_0.tar.bz2
      - name: Configure CMake
        env:
          CONFIGURATION: ${{ matrix.configuration }}
          COMPILER: ${{ matrix.compiler }}
          ARCHITECTURE: ${{ matrix.arch }}
        shell: bash
        run: |
          mkdir build
          cd build
          cmake -DBOOST_ROOT=./boost_1_56_0 -G "Visual Studio 16 2019" -T "v142" -A "$ARCHITECTURE" ..
      - name: Compile
        working-directory: ./build
        env:
          CONFIGURATION: ${{ matrix.configuration }}
          COMPILER: ${{ matrix.compiler }}
        shell: bash
        run: |
          cmake --build . --config "$CONFIGURATION" --target install -- /verbosity:minimal
      - name:  SHARE unit test
          working-directory: ./build/binary/bin
          env:
            CONFIGURATION: ${{ matrix.configuration }}
            COMPILER: ${{ matrix.compiler }}
          shell: bash
          run: |
                ./unit_tests
      - name:  Testing RTC
        working-directory: ./build/binary/bin
        env:
          CONFIGURATION: ${{ matrix.configuration }}
          COMPILER: ${{ matrix.compiler }}
        shell: bash
        run: |
          timeout --signal=SIGABRT 100 ./Kernel -c ./test/test_kernel.json &
          timeout --signal=SIGABRT 100 ./test_rtc
          taskkill //F //IM Kernel.exe
      - name:  Testing inheritance
        working-directory: ./build/binary/bin
        env:
          CONFIGURATION: ${{ matrix.configuration }}
          COMPILER: ${{ matrix.compiler }}
        shell: bash
        run: |
          timeout --signal=SIGABRT 100 ./Kernel &
          timeout --signal=SIGABRT 100 ./test_inheritance
          taskkill //F //IM Kernel.exe
      - name:  Testing errors
        working-directory: ./build/binary/bin
        env:
          CONFIGURATION: ${{ matrix.configuration }}
          COMPILER: ${{ matrix.compiler }}
        shell: bash
        if: matrix.configuration == 'Release'
        run: |
          timeout --signal=SIGABRT 100 ./Kernel &
          timeout --signal=SIGABRT 100 ./test_errors
          taskkill //F //IM Kernel.exe
      - name:  Testing high load
        working-directory: ./build/binary/bin
        env:
          CONFIGURATION: ${{ matrix.configuration }}
          COMPILER: ${{ matrix.compiler }}
        shell: bash
        if: matrix.configuration == 'Release'
        run: |
          timeout --signal=SIGABRT 100 ./Kernel &
          timeout --signal=SIGABRT 100 ./test_of_speed
          taskkill //F //IM Kernel.exe
      - name: Store artifact
        uses: actions/upload-artifact@master
        with:
          name: UDT-bunary-${{ matrix.compiler }}-${{ matrix.arch }}-${{ matrix.configuration }}-${{ github.sha }}
          path: build/binary/