name: CI-MinGW

on: [push]

jobs:
  build_mingw:
    strategy:
      matrix:
        configuration: [Release]
        compiler: [MinGW]
        arch: [Win32]
    name: Windows
    runs-on: windows-2019
    env:
      MSYS_ROOT: ${{ matrix.compiler}}-${{ matrix.arch}}
    steps:
      - name: Prepare Environment
        shell: cmd
        run: |
          choco install msys2 --params="/InstallDir:%GITHUB_WORKSPACE%/%MSYS_ROOT% /NoPath" -y --no-progress
      - name: Install mingwX86 Packages
        shell: cmd
        run: |
          set PATH=%GITHUB_WORKSPACE%/%MSYS_ROOT%;%GITHUB_WORKSPACE%/%MSYS_ROOT%/usr/bin;%GITHUB_WORKSPACE%/%MSYS_ROOT%/mingw64/bin;%PATH%
          pacman --noconfirm -Syu
          pacman --noconfirm -S base-devel mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake mingw-w64-x86_64-boost
      - uses: actions/checkout@v1
#      - name: Install boost
#        shell: bash
#        run: |
#          wget -nv http://downloads.sourceforge.net/project/boost/boost/1.56.0/boost_1_56_0.tar.bz2
#          tar --bzip2 -xf boost_1_56_0.tar.bz2
      - name: Configure CMake
        env:
          CONFIGURATION: ${{ matrix.configuration }}
          COMPILER: ${{ matrix.compiler }}
          ARCHITECTURE: ${{ matrix.arch }}
        shell: cmd
        run: |
          set PATH=%GITHUB_WORKSPACE%/%MSYS_ROOT%/usr/bin/;%GITHUB_WORKSPACE%/%MSYS_ROOT%/mingw64/bin/
          mkdir build
          cd build
          set
          cmake --version
          cmake -DCMAKE_BUILD_TYPE=$CONFIGURATION  -DCMAKE_SH="CMAKE_SH-NOTFOUND" -G "MinGW Makefiles" ..
      - name: Compile
        working-directory: ./build
        env:
          CONFIGURATION: ${{ matrix.configuration }}
          COMPILER: ${{ matrix.compiler }}
        shell: bash
        run: |
          cmake --build . --config "$CONFIGURATION" --target install
      - name:  Testing RTC
        working-directory: ./build/binary/bin
        env:
          CONFIGURATION: ${{ matrix.configuration }}
          COMPILER: ${{ matrix.compiler }}
        shell: bash
        run: |
          timeout --signal=SIGABRT 100 ./Kernel -c ./test/test_kernel.json &
          timeout --signal=SIGABRT 100 ./test_rtc
          taskkill //F //IM Kernel.exe
      - name: Store artifact
        uses: actions/upload-artifact@master
        with:
          name: UDT-bunary-${{ matrix.compiler }}-${{ matrix.arch }}-${{ matrix.configuration }}-${{ github.sha }}
          path: build/binary/